linkWorkspacePackages: deep
saveWorkspaceProtocol: false
savePrefix: '^'

packages:
  - apps/*
  - packages/*
  - features/*/*

onlyBuiltDependencies:
  - esbuild
  - scrollmirror
  - sharp
  - yarn

